packages:
  - 'frontend'
  - 'backend'
  - 'infra'
  - 'scripts'
  - 'shared'

catalog:
  '@aws-lambda-powertools/commons': '2.16.0'
  '@aws-lambda-powertools/logger': '2.16.0'
  '@aws-lambda-powertools/metrics': '2.16.0'
  '@aws-lambda-powertools/tracer': '2.16.0'
  '@aws-sdk/client-cloudformation': '3.772.0'
  '@aws-sdk/client-cloudfront': '3.772.0'
  '@aws-sdk/client-cognito-identity-provider': '3.772.0'
  '@aws-sdk/client-dynamodb': '3.772.0'
  '@aws-sdk/client-s3': '3.772.0'
  '@aws-sdk/client-secrets-manager': '3.772.0'
  '@aws-sdk/client-ssm': '3.772.0'
  '@aws-sdk/client-sts': '3.772.0'
  '@aws-sdk/lib-dynamodb': '3.772.0'
  '@eslint/js': '^9.31.0'
  '@jest/globals': '^29.7.0'
  '@trivago/prettier-plugin-sort-imports': '^5.2.2'
  '@types/jest-when': '^3.5.5'
  '@types/jest': '^29.5.14'
  '@types/ramda': '^0.31.0'
  '@types/mime-types': '^3.0.1'
  '@types/node': '^20.0.0'
  'axios': '^1.8.4'
  'axios-retry': '^4.5.0'
  'dotenv': '^16.4.7'
  'eslint-config-prettier': '^10.1.5'
  'eslint-import-resolver-typescript': '^3.7.0'
  'eslint-plugin-import': '^2.32.0'
  'eslint-plugin-jest': '^29.0.1'
  'eslint-plugin-prettier': '^5.5.1'
  'eslint-plugin-react-hooks': '^5.2.0'
  'eslint-plugin-react-refresh': '^0.4.20'
  'eslint-plugin-react': '^7.37.5'
  'eslint-plugin-unused-imports': '^4.1.4'
  'eslint': '^9.17.0'
  'globals': '^16.3.0'
  'jest-when': '^3.7.0'
  'jest': '^29.7.0'
  'mime-types': '^3.0.1'
  'prettier': '^3.5.3'
  'ramda': '^0.31.3'
  'reflect-metadata': '^0.2.2'
  'ts-jest': '^29.2.6'
  'tsx': '^4.19.2'
  'typescript-eslint': '^8.36.0'
  'typescript': '^5.8.2'
  'zod': '^3.24.1'
